Updating readme with temperature in place of serialNumber
Azure/azure-iot-sdk-csharp pull request #2035
Opened 2021-06-17 00:33 UTC by ericmitt

2021-06-17 01:01 UTC, drwill-ms commented on iothub/device/samples/convention-based-samples/readme.md
> +int temperature = "70";
```suggestion
int temperature = 70;
```

2021-06-17 01:01 UTC, drwill-ms commented on iothub/device/samples/convention-based-samples/readme.md
> +int temperature = "70";
```suggestion
int temperature = 70;
```

2021-06-17 01:01 UTC, drwill-ms commented on iothub/device/samples/convention-based-samples/readme.md
> +int temperature = "70";
```suggestion
int temperature = 70;
```

2021-06-17 01:02 UTC, drwill-ms commented on iothub/device/samples/convention-based-samples/readme.md
> +int temperature = "70";
```suggestion
int temperature = 70;
```

2021-06-17 01:43 UTC, drwill-ms requested changes
Type 'int' should not be initialized to string.

2021-06-17 15:50 UTC, ericmitt reviewed
better to have a double rather an int for the temperature

2021-06-17 17:34 UTC, drwill-ms commented on iothub/device/samples/convention-based-samples/readme.md
> +double temperature = 70;
I see you switched this to a double. If you are going to do that (which I think is a good value for temperature), I think you should change the initialized value to something that doesn't look like an int.

IOW, it should be:

```suggestion
double temperature = 70.0D;
```

2021-06-18 20:19 UTC, drwill-ms approved these changes

2021-06-18 21:24 UTC, merged