Add XML docs for exceptions that can be thrown by ModuleClient.SendEventAsync and DeviceClient.SendEventAsync
Azure/azure-iot-sdk-csharp pull request #2178
Opened 2021-09-25 15:13 UTC by Marusyk

Added XML docs for exceptions that can be thrown by ModuleClient.SendEventAsync and DeviceClient.SendEventAsync
Please review.

Thank you in advance

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x] This pull-request is submitted against the `master` branch.

## Reference/Link to the issue solved with this PR (if any)
Fixes #2176

2021-09-30 21:44 UTC, abhipsaMisra commented
Thank you for submitting this PR. 
There are a couple of more exceptions that could be thrown from these APIs, would you mind adding the below test as well:

```csharp
        /// <exception cref="IotHubCommunicationException">Thrown if the client encounters a transient retryable exception. </exception>
        /// <exception cref="TimeoutException">Thrown if the service does not respond to the request within the timeout specified for the operation.
        /// The timeout values are largely transport protocol specific. Check the corresponding transport settings to see if they can be configured.
        /// The operation timeout for the client can be set using <see cref="OperationTimeoutInMilliseconds"/>.</exception>
        /// <exception cref="OperationCanceledException">Thrown if the service does not respond to the request before the expiration of the passed <see cref="CancellationToken"/>.
        /// If a cancellation token is not supplied to the operation call, a cancellation token with an expiration time of 4 minutes is used.
        /// </exception>
        /// <exception cref="SocketException">Thrown if a socket error occurs.</exception>
        /// <exception cref="WebSocketException">Thrown if an error occurs when performing an operation on a WebSocket connection.</exception>
        /// <exception cref="IOException">Thrown if an I/O error occurs.</exception>
        /// <exception cref="ClosedChannelException">Thrown if the MQTT transport layer closes unexpectedly.</exception>
        /// <exception cref="IotHubException">Thrown if an error occurs when communicating with IoT Hub service.
        /// If <see cref="IotHubException.IsTransient"/> is set to <c>true</c> then it is a transient exception.
        /// If <see cref="IotHubException.IsTransient"/> is set to <c>false</c> then it is a non-transient exception.</exception>
        /// <remarks>
        /// In case of a transient issue, retrying the operation should work. In case of a non-transient issue, inspect the error details and take steps accordingly.
        /// Please note that the above list is not exhaustive.
        /// </remarks>
```

2021-10-03 21:29 UTC, Marusyk commented
@abhipsaMisra done
please review

2021-10-04 16:43 UTC, drwill-ms commented on iothub/device/src/DeviceClient.cs
> +        /// Please note that the above list is not exhaustive.
I realize this text may have been supplied to you by Abhipsa, but I have a small issue with it.

It doesn't specify what list is not exhaustive, and when translated to the web documentation the list of exceptions are likely below the remarks section IIRC.

I suggest we reference the list directly.

```suggestion
        /// Please note that the list of exceptions is not exhaustive.
```

If you'd apply this change (or feel free to improve upon it) to this and all the other cases in this PR, that would be ideal.

2021-10-04 16:43 UTC, drwill-ms requested changes
One small wording change requested.

2021-10-05 17:17 UTC, drwill-ms approved these changes

2021-10-05 17:17 UTC, drwill-ms commented
/azp run

2021-10-05 17:35 UTC, drwill-ms commented
It looks like there is a build failure due to some of the types referenced in the doc comments not being found. You'll need to add some using statements up top to make sure the types are known.

2021-10-05 18:55 UTC, drwill-ms commented
/azp run

2021-10-05 19:24 UTC, Marusyk commented
I can`t see the build error because  - 401 - Uh-oh, you do not have access.

2021-10-05 20:15 UTC, drwill-ms commented
> I can`t see the build error because - 401 - Uh-oh, you do not have access.

No problem. It is an internal pipeline. The error is a failed test due to service throttling. I'm rerunning the failed pipelines. I'm sure it'll go through and then I'll merge it.

It is looking good at this point. Thank you very much for your quick responses along the way.

2021-10-05 22:14 UTC, merged