Features/provisioning sdk rbac e2 e tests
Azure/azure-iot-sdk-csharp pull request #2284
Opened 2022-01-14 18:11 UTC by dylanbulfinMS

## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `main` branch.

## Description of the changes

## Reference/Link to the issue solved with this PR (if any)

2022-01-14 18:11 UTC, dylanbulfinMS commented
/azp run

2022-01-14 18:49 UTC, drwill-ms commented on e2e/test/config/TestConfiguration.Provisioning.cs
> +            public class ConnectionStringParser
Prefer to put classes in their own file.

2022-01-14 18:51 UTC, drwill-ms commented on e2e/test/config/TestConfiguration.Provisioning.cs
> +                    string[] parts = connectionString.Split(';');
Consider splitting on ; and =, and putting the kvps in a dictionary.

2022-01-14 18:51 UTC, drwill-ms commented on e2e/test/config/TestConfiguration.Provisioning.cs
> +                public string ProvisioningHostName { get; private set; }
properties above methods (ordering in a class)

2022-01-14 18:51 UTC, drwill-ms commented on e2e/test/config/TestConfiguration.Provisioning.cs
> +                public string DeviceID { get; private set; }
```suggestion
                public string DeviceId { get; private set; }
```

2022-01-14 18:54 UTC, drwill-ms commented on e2e/test/provisioning/ProvisioningServiceClientE2ETests.cs
> +            IndividualEnrollment individualEnrollment = await CreateIndividualEnrollment(provisioningServiceClient, AttestationMechanismType.SymmetricKey, null, AllocationPolicy.Static, null, null, n
When lines get this long, we like to break them up. For this one, parameters can each get their own line. Also, in product code and tests (not samples) we append `.ConfigureAwait(false)` to async calls.

```suggestion
            IndividualEnrollment individualEnrollment = await CreateIndividualEnrollment(
                    provisioningServiceClient,
                    AttestationMechanismType.SymmetricKey,
                    null,
                    AllocationPolicy.Static,
                    null,
                    null,
                    null)
                .ConfigureAwait(false);
```

2022-01-14 18:54 UTC, drwill-ms commented on e2e/test/provisioning/ProvisioningServiceClientE2ETests.cs
> +            Assert.IsNotNull(individualEnrollmentResult);
Prefer FluentAssertions.

```suggestion
            individualEnrollmentResult.Should().NotBeNull();
```

2022-01-14 18:55 UTC, drwill-ms requested changes
Inline comments.

2022-01-25 19:21 UTC, azabbasi commented on e2e/test/provisioning/ProvisioningServiceClientE2ETests.cs
> +            IndividualEnrollment individualEnrollment = await CreateIndividualEnrollment(provisioningServiceClient, AttestationMechanismType.SymmetricKey, null, AllocationPolicy.Static, null, null, n
```suggestion
            IndividualEnrollment individualEnrollment = await CreateIndividualEnrollment(
                    provisioningServiceClient, 
                    AttestationMechanismType.SymmetricKey, 
                    null, 
                    AllocationPolicy.Static, 
                    null, 
                    null, 
                    null);
```

2022-01-25 21:34 UTC, azabbasi commented on e2e/test/provisioning/ProvisioningServiceClientE2ETests.cs
> +            Assert.IsNotNull(individualEnrollmentResult);
Please use fluent assertion instead.

2022-01-25 23:58 UTC, drwill-ms commented
/azp run

2022-01-26 00:24 UTC, dylanbulfinMS commented
/azp run

2022-01-26 00:37 UTC, dylanbulfinMS commented
/azp run

2022-01-26 15:09 UTC, jamdavi commented on e2e/test/provisioning/ConnectionStringParser.cs
> +namespace Microsoft.Azure.Devices.E2ETests.provisioning
Casing on the namespace.

```suggestion
namespace Microsoft.Azure.Devices.E2ETests.Provisioning
```

2022-01-26 15:09 UTC, jamdavi commented on e2e/test/config/TestConfiguration.Provisioning.cs
> +using Microsoft.Azure.Devices.E2ETests.provisioning;
Will need to be changed with other casing request.

```suggestion
using Microsoft.Azure.Devices.E2ETests.Provisioning;
```

2022-01-31 23:48 UTC, dylanbulfinMS commented
/azp run

2022-01-31 23:57 UTC, dylanbulfinMS commented
/azp run

2022-02-01 00:34 UTC, drwill-ms commented
/azp run

2022-02-01 00:54 UTC, drwill-ms approved these changes

2022-02-01 18:39 UTC, azabbasi approved these changes

2022-02-01 18:41 UTC, azabbasi commented
/azp run

2022-02-01 22:36 UTC, merged