Move set retry policy to ClientOptions
Azure/azure-iot-sdk-csharp pull request #2824
Opened 2022-10-05 16:19 UTC by ngastelum-ms

2022-10-05 19:43 UTC, drwill-ms commented on CodeMaid.config
> +        <value>False</value>
You may want to call out why this has changed.

2022-10-05 19:44 UTC, drwill-ms commented on iothub/device/src/IotHubClientOptions.cs
> +        /// Defaults to a near infinite exponential backoff. If set to null, will use <see cref="NoRetry"/> to perform no retries
near infinite?

Please document other available built-in retry polies available to the user.

End the sentence with punctuation.

2022-10-05 19:45 UTC, drwill-ms commented on iothub/device/src/Pipeline/ClientPipelineBuilder.cs
> +                    retryHandler.SetRetryPolicy(retryPolicy);
```suggestion
                    retryHandler.SetRetryPolicy(retryPolicy ?? new NoRetry());
```

2022-10-05 19:45 UTC, drwill-ms requested changes
Migration document update?

2022-10-05 20:06 UTC, ngastelum-ms commented on CodeMaid.config
> +        <value>False</value>
Turned off CodeMaid's auto cleanup on save in order to avoid this bug https://github.com/codecadwallader/codemaid/issues/860

2022-10-05 20:46 UTC, drwill-ms commented on SDK v2 migration guide.md
> +| `SetRetryPolicy` | `IoTHubClientOptions.RetryPolicy` |
```suggestion
| `SetRetryPolicy(...)` | `IoTHubClientOptions.RetryPolicy` |
```

2022-10-05 20:47 UTC, drwill-ms approved these changes

2022-10-05 21:12 UTC, patilsnr approved these changes

2022-10-05 21:12 UTC, patilsnr commented on SDK v2 migration guide.md
> +- Some options that were previously set in the `DeviceClient` constructor are now in the optional `IotHubClientOptions` parameter
+1

2022-10-05 21:12 UTC, patilsnr commented on iothub/device/src/IotHubBaseClient.cs
> +}
nit: shouldn't we have a newline at the end of our files?

2022-10-05 21:39 UTC, ngastelum-ms commented on SDK v2 migration guide.md
> +- Some options that were previously set in the `DeviceClient` constructor are now in the optional `IotHubClientOptions` parameter
Oops, not sure how that happened

2022-10-05 22:02 UTC, ngastelum-ms commented
/azp run

2022-10-05 23:46 UTC, ngastelum-ms commented
/azp run

2022-10-06 18:02 UTC, ngastelum-ms commented
/azp run

2022-10-07 19:12 UTC, ngastelum-ms commented
/azp run

2022-10-07 19:41 UTC, ngastelum-ms commented
/azp run

2022-10-07 19:58 UTC, ngastelum-ms commented
/azp run

2022-10-07 20:30 UTC, ngastelum-ms commented
/azp run

2022-10-11 23:43 UTC, ngastelum-ms commented
/azp run

2022-10-12 00:10 UTC, ngastelum-ms commented
/azp run

2022-10-12 18:04 UTC, ngastelum-ms commented
/azp run

2022-10-12 18:33 UTC, merged