Update CODEOWNERS
Azure/azure-iot-sdk-csharp pull request #2908
Opened 2022-10-24 16:33 UTC by andyk-ms

Adding Sophia

2022-10-24 16:36 UTC, schoims requested changes

2022-10-24 16:36 UTC, schoims commented on .github/CODEOWNERS
> +*	@drwill-ms @timtay-microsoft @abhipsaMisra @andyk-ms @brycewang-microsoft @tmahmood-microsoft @ngastelum-ms @patilsnr @schomims
there is a typo. my id is @schoims

2022-10-24 16:38 UTC, schoims approved these changes

2022-10-24 16:38 UTC, andyk-ms commented on .github/CODEOWNERS
> +*	@drwill-ms @timtay-microsoft @abhipsaMisra @andyk-ms @brycewang-microsoft @tmahmood-microsoft @ngastelum-ms @patilsnr @schomims
updated.

2022-10-24 16:39 UTC, timtay-microsoft approved these changes

2022-10-24 16:41 UTC, brycewang-microsoft approved these changes

2022-11-09 17:58 UTC, schoims commented
/azp run

2022-11-09 18:22 UTC, schoims commented
/azp run

2022-11-09 18:40 UTC, merged